### ISSUE TITLE
UnsatisfiedLinkError on Mac OS

### ISSUE THREAD

**Issue by Asutu** [mozack/abra2#13]
Hi,

when trying to run the pre-compiled abra2-2.11.jar on a Mac I get this error:

```
INFO	Fri Oct 06 16:02:15 BST 2017	Abra version: 2.11
INFO	Fri Oct 06 16:02:15 BST 2017	Abra params: [/Users/pmca/Software/ngs/abra2/abra2-2.11.jar --in ind123.bwa.clean.bam --out ind123.bwa.clean.abra.bam --mapq 10 --ref /Users/pmca/Scripts/test_data/ngs-data/snp1-illumina/refseqs.3contigs.100kb.fas]
INFO	Fri Oct 06 16:02:15 BST 2017	ABRA version: 2.11
INFO	Fri Oct 06 16:02:15 BST 2017	input0: ind123.bwa.clean.bam
INFO	Fri Oct 06 16:02:15 BST 2017	output0: ind123.bwa.clean.abra.bam
INFO	Fri Oct 06 16:02:15 BST 2017	regions: null
INFO	Fri Oct 06 16:02:15 BST 2017	reference: /Users/pmca/Scripts/test_data/ngs-data/snp1-illumina/refseqs.3contigs.100kb.fas
INFO	Fri Oct 06 16:02:15 BST 2017	num threads: 4
INFO	Fri Oct 06 16:02:15 BST 2017	minEdgeFrequency: 0
minNodeFrequncy: 1
minContigLength: -1
minBaseQuality: 20
minReadCandidateFraction: 0.01
maxAverageRegionDepth: 1000
minEdgeRatio: 0.01

INFO	Fri Oct 06 16:02:15 BST 2017	paired end: true
INFO	Fri Oct 06 16:02:15 BST 2017	isSkipAssembly: false
INFO	Fri Oct 06 16:02:15 BST 2017	useSoftClippedReads: true
INFO	Fri Oct 06 16:02:15 BST 2017	SW scoring: [8, 32, 48, 1]
INFO	Fri Oct 06 16:02:15 BST 2017	Soft clip params: [16, 13, 80, 15]
INFO	Fri Oct 06 16:02:15 BST 2017	Java version: 1.8.0_60
INFO	Fri Oct 06 16:02:15 BST 2017	hostname: MacBook-Pro.local
INFO	Fri Oct 06 16:02:15 BST 2017	SG match,mismatch,gap_open_penalty,gap_extend_penalty: 8,-32,-48,-1
INFO	Fri Oct 06 16:02:15 BST 2017	Using temp directory: /var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563
INFO	Fri Oct 06 16:02:15 BST 2017	Loading native library from: /var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so
ERROR	Fri Oct 06 16:02:15 BST 2017	Error loading: libAbra.so from : /var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563
java.lang.UnsatisfiedLinkError: /private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so: dlopen(/private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so, 1): no suitable image found.  Did find:
	/private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:45)
	at abra.ReAligner.init(ReAligner.java:1533)
	at abra.ReAligner.reAlign(ReAligner.java:159)
	at abra.ReAligner.run(ReAligner.java:1711)
	at abra.Abra.main(Abra.java:12)
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so: dlopen(/private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so, 1): no suitable image found.  Did find:
	/private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:57)
	at abra.ReAligner.init(ReAligner.java:1533)
	at abra.ReAligner.reAlign(ReAligner.java:159)
	at abra.ReAligner.run(ReAligner.java:1711)
	at abra.Abra.main(Abra.java:12)
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so: dlopen(/private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so, 1): no suitable image found.  Did find:
	/private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:45)
	... 4 more
```

The command line to call ABRA2 was:
```
java -jar ~/Software/ngs/abra2/abra2-2.11.jar --in ind123.bwa.clean.bam --out ind123.bwa.clean.abra.bam --mapq 10 --ref /Users/pmca/Scripts/test_data/ngs-data/snp1-illumina/refseqs.3contigs.100kb.fas
```

if I do an `ls` in the directory ABRA2 claims to not find the library I see:
```
> ls -l /private/var/folders/wb/_zmb2_3n1cj6clc4_x1yv5300000gn/T/abra2_2fdaca04-d870-4fa6-9539-dbd4f569928a6991233934775758563/
total 1512
-rw-r--r--  1 pmca  staff  770248  6 Oct 16:02 libAbra.so
```

My system is:
Darwin MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64

Thanks for the help.
Pedro

**Comment by mozack** [comment]
The precompiled release was built on Centos 7 and I would not expect it to work on MacOS.  You could try building yourself. You'll need an installation of the jdk8, maven and g++ to do so.  I'm afraid I'm unable to directly support MacOS at this time, but can try to provide guidance if you're willing to try building yourself.

**Comment by Asutu** [comment]
Thanks, that makes sense. Ultimately the tool will be run on a Linux system. I just wanted to give it a try first, which I usually do on my laptop. I'll try to compile it myself, and I might get here again if there's something I'm really strugling with.

Thanks again for the help.
