### ISSUE TITLE
Error when running abra2: Inappropriate call if not paired read

### ISSUE THREAD

**Issue by thchen86** [mozack/abra2#3]
Hi Mozack, 

I tried to use novoalign3 to map the pair-end DNA reads and samtools to sort the reads into a sorted bam file. After that, I used abra2 to realign the reads but got the following error after processing the reads: 

java.lang.IllegalStateException: Inappropriate call if not paired read
        at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:871)
        at htsjdk.samtools.SAMRecord.getFirstOfPairFlag(SAMRecord.java:929)
        at abra.SortedSAMWriter.getOriginalReadInfo(SortedSAMWriter.java:300)
        at abra.SortedSAMWriter.processChromosome(SortedSAMWriter.java:208)
        at abra.SortedSAMWriter.outputFinal(SortedSAMWriter.java:150)
        at abra.SortedSAMWriterRunnable.go(SortedSAMWriterRunnable.java:18)
        at abra.AbraRunnable.run(AbraRunnable.java:20)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745) 

Do you have an idea how should this error be resolved?

Thanks,
Tenghui

**Comment by mozack** [comment]
If you have paired end reads, the "read paired" flag should be set (0x01).  You may need to investigate why Novoalign is not setting that flag.  Is it possible that not all of your reads are paired?

**Comment by thchen86** [comment]
@mozack Thank you for the quick reply, it did showed in the bam file that the "read paired" bit flag was not available, I will try to figure out if it has something to do with the novoalign. But it is definitely not an issue about abra2.

**Comment by mozack** [comment]
OK.  I'll close this then.  Please feel free to re-open if you see any ABRA2 specific issues.
