### ISSUE TITLE
compilation terminated during make

### ISSUE THREAD

**Issue by zhoutengsheng** [mozack/abra2#37]
Hi,

I keep facing this issue when making the Makefile

rm -rf target
mvn clean
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------------< abra2:abra2 >-----------------------------
[INFO] Building abra 2.19
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ abra2 ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.197 s
[INFO] Finished at: 2019-07-20T23:40:00-06:00
[INFO] ------------------------------------------------------------------------
mkdir target
g++ -g -O2 -Isrc/main/c -I/Users/tzhou_admin/anaconda3/include -I/Users/tzhou_admin/anaconda3/include/linux -shared -fPIC src/main/c/assembler.cpp src/main/c/sg_aligner.cpp -o target/libAbra.so
src/main/c/assembler.cpp:1:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
src/main/c/sg_aligner.cpp:1:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.

Could you please help figure out what is problem during the installation?

Thanks very much!

**Comment by mozack** [comment]
Unless you have a specific reason to compile, try using one of the precompiled releases.

Otherwise, you'll need to configure your system to have the C standard library files available to the compiler.

https://www.google.com/search?q=fatal+error%3A+stdio.h%3A+No+such+file+or+directory&oq=fatal+error%3A+stdio.h%3A+No+such+file+or+directory

**Comment by zhoutengsheng** [comment]
> Unless you have a specific reason to compile, try using one of the precompiled releases.
> 
> Otherwise, you'll need to configure your system to have the C standard library files available to the compiler.
> 
> https://www.google.com/search?q=fatal+error%3A+stdio.h%3A+No+such+file+or+directory&oq=fatal+error%3A+stdio.h%3A+No+such+file+or+directory

Hi,
Thanks very much for your reply!

I tried to use the precompiled abra2 version to run the data as the following command in my Macbook Pro
/Users/tzhou_admin/dagram/ABRA/abra2-2.19.jar --in sample1.bam --out normal.abra.bam --ref test.fa --threads 4 --tmpdir tmpdir

And, here is what I got; I did not the output bam file. Sorry for keepoing bothering you, I am trying to use your program to analyze my NGs data for my cripr -edited lines.

INFO	Mon Jul 22 15:23:51 CST 2019	ABRA version: 2.19
INFO	Mon Jul 22 15:23:51 CST 2019	input0: sample1.bam
INFO	Mon Jul 22 15:23:51 CST 2019	output0: normal.abra.bam
INFO	Mon Jul 22 15:23:51 CST 2019	regions: null
INFO	Mon Jul 22 15:23:51 CST 2019	reference: test.fa
INFO	Mon Jul 22 15:23:51 CST 2019	num threads: 4
INFO	Mon Jul 22 15:23:51 CST 2019	minEdgeFrequency: 0
minNodeFrequncy: 1
minContigLength: -1
minBaseQuality: 20
minReadCandidateFraction: 0.01
maxAverageRegionDepth: 1000
minEdgeRatio: 0.01

INFO	Mon Jul 22 15:23:51 CST 2019	paired end: true
INFO	Mon Jul 22 15:23:51 CST 2019	isSkipAssembly: false
INFO	Mon Jul 22 15:23:51 CST 2019	useSoftClippedReads: true
INFO	Mon Jul 22 15:23:51 CST 2019	SW scoring: [8, 32, 48, 1]
INFO	Mon Jul 22 15:23:51 CST 2019	Soft clip params: [16, 13, 80, 15]
INFO	Mon Jul 22 15:23:51 CST 2019	Java version: 1.8.0_152-release
INFO	Mon Jul 22 15:23:52 CST 2019	hostname: Y10-L022.local
INFO	Mon Jul 22 15:23:52 CST 2019	SG match,mismatch,gap_open_penalty,gap_extend_penalty: 8,-32,-48,-1
INFO	Mon Jul 22 15:23:52 CST 2019	Using temp directory: tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120
INFO	Mon Jul 22 15:23:52 CST 2019	Loading native library from: /Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so
ERROR	Mon Jul 22 15:23:52 CST 2019	Error loading: libAbra.so from : tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120
java.lang.UnsatisfiedLinkError: /Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: dlopen(/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so, 1): no suitable image found.  Did find:
	/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:45)
	at abra.ReAligner.init(ReAligner.java:1670)
	at abra.ReAligner.reAlign(ReAligner.java:166)
	at abra.ReAligner.run(ReAligner.java:1851)
	at abra.Abra.main(Abra.java:12)
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: dlopen(/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so, 1): no suitable image found.  Did find:
	/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:57)
	at abra.ReAligner.init(ReAligner.java:1670)
	at abra.ReAligner.reAlign(ReAligner.java:166)
	at abra.ReAligner.run(ReAligner.java:1851)
	at abra.Abra.main(Abra.java:12)
Caused by: java.lang.UnsatisfiedLinkError: /Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: dlopen(/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so, 1): no suitable image found.  Did find:
	/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/tzhou_admin/Desktop/crispr_ngs/abra2-master/test-data/tmpdir/abra2_0562c09b-286f-4b6f-ae3e-110bef1e038e2205517086672997120/libAbra.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:45)
	... 4 more

**Comment by mozack** [comment]
Ah, yes.  The precompiled versions will not work on Mac.  A quick Google search suggests to install xcode.  I have not attempted to run on Mac myself.
