### ISSUE TITLE
Bed file format

### ISSUE THREAD

**Issue by V-Catherine** [mozack/abra2#43]
My bed file with its one-line header made abra2 crash with the following error: 
Loading target regions from : target.bed
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at abra.RegionLoader.load(RegionLoader.java:49)
	at abra.ReAligner.getRegions(ReAligner.java:1347)
	at abra.ReAligner.loadRegions(ReAligner.java:1379)
	at abra.ReAligner.reAlign(ReAligner.java:180)
	at abra.ReAligner.run(ReAligner.java:1833)
	at abra.Abra.main(Abra.java:12)
Once I removed the header line, it run well. Many bed files have headers so maybe it would be useful to allow them.
Thanks in advance

**Comment by mozack** [comment]
We currently skip header lines starting with what I understand to be the standard bed header text.  i.e. browser, track or #

Let me know if you are seeing otherwise.
