### ISSUE TITLE
Unknown format conversion exception

### ISSUE THREAD

**Issue by abhiku0007** [mozack/abra2#56]
khanabadosh@KhanaBadosh:/mnt/c/Users/Abhishek Kumar/Desktop/NGS_Data_Analysis/Test1$ java -Xmx2g -jar abra2-2.23.jar  --in Sorted_out.bam --out
Sorted_out.abra.bam --ref S288C_reference_sequence_R64-2-1_20150113.fsa threads 4 --tmpdir tmpdir > abra.log
INFO    Sat Aug 26 18:25:56 IST 2023    Abra version: 2.23
Exception in thread "main" java.util.UnknownFormatConversionException: Conversion = 'K'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
        at java.util.Formatter.parse(Formatter.java:2560)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at abra.Logger.info(Logger.java:45)
        at abra.ReAligner.run(ReAligner.java:1739)
        at abra.Abra.main(Abra.java:12)

**Comment by SanjayanAri** [comment]
❯ java -Xmx6G -jar abra2-2.24.jar --in sortedsamatcc927d.bam --out sortedreasamatcc927d.abra.bam --ref mycoatcc927dna.fasta --threads 4 --tmpdir tmpdir > abra.log
INFO	Mon Sep 02 12:20:29 IST 2024	Abra version: 2.24
Exception in thread "main" java.util.UnknownFormatConversionException: Conversion = 'w'
	at java.base/java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2839)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2865)
	at java.base/java.util.Formatter.parse(Formatter.java:2713)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at abra.Logger.info(Logger.java:45)
	at abra.ReAligner.run(ReAligner.java:1739)
	at abra.Abra.main(Abra.java:12)
	
	even I got this type of error, how to solve it ?
